{
    'name': 'Practical Vrunda',
    'summary': """Practical Test Module""",
    "description": """Test Module""",
    "author": "Bista Solutions Pvt.Ltd",
    "license": "LGPL-3",
    "version": "18.0",
    "depends": ['base','sale','purchase','mail','sale_stock'],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/pharmacy_data.xml',
        'data/email_template.xml',
        'wizards/add_product_views.xml',
        'views/pharmacy_views.xml',
        'views/product_template_views.xml',
        'views/account_move_views.xml',
        'views/mail_activity_schedule_views.xml',
        'views/sale_order_views.xml',
        'views/report_deliveryslip.xml',
        'views/res_config_settings_views.xml',
        'views/sale_stock_view.xml',
        'views/stock_picking_views.xml',
    ],
}