from . import patient
from . import appointment
from . import doctor
from . import hospital
from . import hospital_specialization
from . import prescription
from . import prescription_line
from . import res_partner
from . import stock_picking
from . import stock_move