{
    'name': 'Bista HMS',
    'summary': """Hospital Management System""",
    "description": """this app will help to manage hospital""",
    "author": "Bista Solutions Pvt.Ltd",
    "version": "18.0",
    "depends": ['base','product','sale','mail','stock'],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/email_template.xml',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'views/res_patient_view.xml',
        'views/appointment_view.xml',
        'views/res_doctor_view.xml',
        'views/hospital_specialization_view.xml',
        'views/prescription_view.xml',
        'views/report.xml',
        'views/prescription_report_template.xml',
    ],
}