from . import pharmacy
from . import product
from . import account_move
from . import stock_picking
from . import mail_activity_schedule
from . import sale_order
from . import purchase_order
from . import res_company
from . import res_config_settings
from . import sale_order
